// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lb/rps/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateStudent defines the MsgCreateStudent request type
type MsgCreateStudent struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age  uint64 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
}

func (m *MsgCreateStudent) Reset()         { *m = MsgCreateStudent{} }
func (m *MsgCreateStudent) String() string { return proto.CompactTextString(m) }
func (*MsgCreateStudent) ProtoMessage()    {}
func (*MsgCreateStudent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1eea8fddb946f7d, []int{0}
}
func (m *MsgCreateStudent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateStudent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateStudent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateStudent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateStudent.Merge(m, src)
}
func (m *MsgCreateStudent) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateStudent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateStudent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateStudent proto.InternalMessageInfo

func (m *MsgCreateStudent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgCreateStudent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateStudent) GetAge() uint64 {
	if m != nil {
		return m.Age
	}
	return 0
}

// MsgCreateStudent defines the MsgCreateStudent response type
type MsgCreateStudentResponse struct {
}

func (m *MsgCreateStudentResponse) Reset()         { *m = MsgCreateStudentResponse{} }
func (m *MsgCreateStudentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateStudentResponse) ProtoMessage()    {}
func (*MsgCreateStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1eea8fddb946f7d, []int{1}
}
func (m *MsgCreateStudentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateStudentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateStudentResponse.Merge(m, src)
}
func (m *MsgCreateStudentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateStudentResponse proto.InternalMessageInfo

// MsgMakeMove defines the MsgMakeMove request type
type MsgMakeMove struct {
	// Player is the message sender
	Player    string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	GameIndex uint64 `protobuf:"varint,2,opt,name=game_index,json=gameIndex,proto3" json:"game_index,omitempty"`
	Move      string `protobuf:"bytes,3,opt,name=move,proto3" json:"move,omitempty"`
}

func (m *MsgMakeMove) Reset()         { *m = MsgMakeMove{} }
func (m *MsgMakeMove) String() string { return proto.CompactTextString(m) }
func (*MsgMakeMove) ProtoMessage()    {}
func (*MsgMakeMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1eea8fddb946f7d, []int{2}
}
func (m *MsgMakeMove) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMakeMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMakeMove.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMakeMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMakeMove.Merge(m, src)
}
func (m *MsgMakeMove) XXX_Size() int {
	return m.Size()
}
func (m *MsgMakeMove) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMakeMove.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMakeMove proto.InternalMessageInfo

func (m *MsgMakeMove) GetPlayer() string {
	if m != nil {
		return m.Player
	}
	return ""
}

func (m *MsgMakeMove) GetGameIndex() uint64 {
	if m != nil {
		return m.GameIndex
	}
	return 0
}

func (m *MsgMakeMove) GetMove() string {
	if m != nil {
		return m.Move
	}
	return ""
}

// MsgMakeMove defines the MsgMakeMove response type
type MsgMakeMoveResponse struct {
}

func (m *MsgMakeMoveResponse) Reset()         { *m = MsgMakeMoveResponse{} }
func (m *MsgMakeMoveResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMakeMoveResponse) ProtoMessage()    {}
func (*MsgMakeMoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1eea8fddb946f7d, []int{3}
}
func (m *MsgMakeMoveResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMakeMoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMakeMoveResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMakeMoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMakeMoveResponse.Merge(m, src)
}
func (m *MsgMakeMoveResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMakeMoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMakeMoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMakeMoveResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateStudent)(nil), "lb.rps.v1.MsgCreateStudent")
	proto.RegisterType((*MsgCreateStudentResponse)(nil), "lb.rps.v1.MsgCreateStudentResponse")
	proto.RegisterType((*MsgMakeMove)(nil), "lb.rps.v1.MsgMakeMove")
	proto.RegisterType((*MsgMakeMoveResponse)(nil), "lb.rps.v1.MsgMakeMoveResponse")
}

func init() { proto.RegisterFile("lb/rps/v1/tx.proto", fileDescriptor_a1eea8fddb946f7d) }

var fileDescriptor_a1eea8fddb946f7d = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xbd, 0x6e, 0xe2, 0x40,
	0x10, 0x66, 0x0d, 0xc7, 0x9d, 0x17, 0x9d, 0x84, 0xf6, 0xe0, 0xce, 0xe7, 0xd3, 0x59, 0xc8, 0x69,
	0x10, 0x52, 0x6c, 0x91, 0x74, 0x74, 0x21, 0x55, 0x0a, 0x17, 0x31, 0x5d, 0x1a, 0x64, 0xf0, 0x68,
	0x63, 0x61, 0x7b, 0x2d, 0xaf, 0x63, 0x41, 0x17, 0xe5, 0x09, 0xf2, 0x0e, 0x79, 0x01, 0x8a, 0x3c,
	0x44, 0x4a, 0x94, 0x2a, 0x65, 0x04, 0x05, 0xaf, 0x11, 0xad, 0x7f, 0x12, 0x40, 0x51, 0xba, 0x6f,
	0xbe, 0xf9, 0x66, 0xbe, 0xd9, 0xfd, 0x30, 0xf1, 0x27, 0x66, 0x1c, 0x71, 0x33, 0xed, 0x9b, 0xc9,
	0xdc, 0x88, 0x62, 0x96, 0x30, 0x22, 0xfb, 0x13, 0x23, 0x8e, 0xb8, 0x91, 0xf6, 0xd5, 0x3f, 0x53,
	0xc6, 0x03, 0xc6, 0xcd, 0x80, 0x53, 0x21, 0x09, 0x38, 0xcd, 0x35, 0xea, 0xdf, 0xbc, 0x31, 0xce,
	0x2a, 0x33, 0x2f, 0x8a, 0x56, 0x8b, 0x32, 0xca, 0x72, 0x5e, 0xa0, 0x82, 0x6d, 0xef, 0x18, 0x2d,
	0x22, 0x28, 0xc4, 0xfa, 0x0c, 0x37, 0x2d, 0x4e, 0xcf, 0x63, 0x70, 0x12, 0x18, 0x25, 0x37, 0x2e,
	0x84, 0x09, 0xe9, 0x62, 0xc9, 0x73, 0x15, 0xd4, 0x41, 0x5d, 0x79, 0xa8, 0x3c, 0x3f, 0x1e, 0xb7,
	0x8a, 0xf5, 0x67, 0xae, 0x1b, 0x03, 0xe7, 0xa3, 0x24, 0xf6, 0x42, 0x6a, 0x4b, 0x9e, 0x4b, 0x08,
	0xae, 0x85, 0x4e, 0x00, 0x8a, 0x24, 0xb4, 0x76, 0x86, 0x49, 0x13, 0x57, 0x1d, 0x0a, 0x4a, 0xb5,
	0x83, 0xba, 0x35, 0x5b, 0xc0, 0xc1, 0xf7, 0xbb, 0xed, 0xb2, 0x27, 0x79, 0xae, 0xae, 0x62, 0xe5,
	0xd0, 0xcc, 0x06, 0x1e, 0xb1, 0x90, 0x83, 0x0e, 0xb8, 0x61, 0x71, 0x6a, 0x39, 0x33, 0xb0, 0x58,
	0x0a, 0xe4, 0x37, 0xae, 0x47, 0xbe, 0xb3, 0x80, 0x38, 0xbf, 0xc3, 0x2e, 0x2a, 0xf2, 0x1f, 0x63,
	0xea, 0x04, 0x30, 0xf6, 0x42, 0x17, 0xe6, 0x99, 0x6f, 0xcd, 0x96, 0x05, 0x73, 0x21, 0x08, 0x71,
	0x50, 0xc0, 0xd2, 0xdc, 0x5d, 0xb6, 0x33, 0x3c, 0x68, 0x08, 0xfb, 0x62, 0x5e, 0x6f, 0xe3, 0x5f,
	0x3b, 0x36, 0xa5, 0xfb, 0xc9, 0x03, 0xc2, 0x55, 0x8b, 0x53, 0x72, 0x89, 0x7f, 0xee, 0xff, 0xc5,
	0x3f, 0xe3, 0x3d, 0x0c, 0xe3, 0xf0, 0x76, 0xf5, 0xe8, 0x8b, 0x66, 0xb9, 0x9a, 0x0c, 0xf1, 0x8f,
	0x8f, 0x57, 0xed, 0x0f, 0x94, 0xbc, 0xaa, 0x7d, 0xce, 0x97, 0x3b, 0xd4, 0x6f, 0xb7, 0xdb, 0x65,
	0x0f, 0x0d, 0xcd, 0xa7, 0xb5, 0x86, 0x56, 0x6b, 0x0d, 0xbd, 0xae, 0x35, 0x74, 0xbf, 0xd1, 0x2a,
	0xab, 0x8d, 0x56, 0x79, 0xd9, 0x68, 0x95, 0xab, 0xf6, 0xf4, 0xda, 0xf1, 0x7d, 0x08, 0x29, 0x98,
	0xf3, 0x2c, 0xe6, 0x2c, 0xe3, 0x49, 0x3d, 0x0b, 0xf9, 0xf4, 0x2d, 0x00, 0x00, 0xff, 0xff, 0xaf,
	0xe1, 0x44, 0xa3, 0x66, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreateStudent creates an student
	CreateStudent(ctx context.Context, in *MsgCreateStudent, opts ...grpc.CallOption) (*MsgCreateStudentResponse, error)
	// MakeMove submit a move to the specific game
	MakeMove(ctx context.Context, in *MsgMakeMove, opts ...grpc.CallOption) (*MsgMakeMoveResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateStudent(ctx context.Context, in *MsgCreateStudent, opts ...grpc.CallOption) (*MsgCreateStudentResponse, error) {
	out := new(MsgCreateStudentResponse)
	err := c.cc.Invoke(ctx, "/lb.rps.v1.Msg/CreateStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MakeMove(ctx context.Context, in *MsgMakeMove, opts ...grpc.CallOption) (*MsgMakeMoveResponse, error) {
	out := new(MsgMakeMoveResponse)
	err := c.cc.Invoke(ctx, "/lb.rps.v1.Msg/MakeMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreateStudent creates an student
	CreateStudent(context.Context, *MsgCreateStudent) (*MsgCreateStudentResponse, error)
	// MakeMove submit a move to the specific game
	MakeMove(context.Context, *MsgMakeMove) (*MsgMakeMoveResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateStudent(ctx context.Context, req *MsgCreateStudent) (*MsgCreateStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStudent not implemented")
}
func (*UnimplementedMsgServer) MakeMove(ctx context.Context, req *MsgMakeMove) (*MsgMakeMoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeMove not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateStudent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.rps.v1.Msg/CreateStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateStudent(ctx, req.(*MsgCreateStudent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MakeMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMakeMove)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MakeMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.rps.v1.Msg/MakeMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MakeMove(ctx, req.(*MsgMakeMove))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lb.rps.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStudent",
			Handler:    _Msg_CreateStudent_Handler,
		},
		{
			MethodName: "MakeMove",
			Handler:    _Msg_MakeMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lb/rps/v1/tx.proto",
}

func (m *MsgCreateStudent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateStudent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateStudent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Age != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Age))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateStudentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateStudentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateStudentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgMakeMove) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMakeMove) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMakeMove) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Move) > 0 {
		i -= len(m.Move)
		copy(dAtA[i:], m.Move)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Move)))
		i--
		dAtA[i] = 0x1a
	}
	if m.GameIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.GameIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Player) > 0 {
		i -= len(m.Player)
		copy(dAtA[i:], m.Player)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Player)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMakeMoveResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMakeMoveResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMakeMoveResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateStudent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Age != 0 {
		n += 1 + sovTx(uint64(m.Age))
	}
	return n
}

func (m *MsgCreateStudentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgMakeMove) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Player)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.GameIndex != 0 {
		n += 1 + sovTx(uint64(m.GameIndex))
	}
	l = len(m.Move)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgMakeMoveResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateStudent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateStudent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateStudent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Age", wireType)
			}
			m.Age = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Age |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateStudentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateStudentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateStudentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMakeMove) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMakeMove: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMakeMove: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Player", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Player = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameIndex", wireType)
			}
			m.GameIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GameIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Move", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Move = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMakeMoveResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMakeMoveResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMakeMoveResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
